### ISSUE TITLE
CI is not integrated in repo

### ISSUE THREAD

**Issue by garg-anuj** [jboss-outreach/rest-android#2]
decide between travis-ci and circle-ci. add config file and readme.md icon of selected to repository.

**Comment by garg-anuj** [comment]
@m-murad @shubhamvashisht @nimit95 please discuss on it

**Comment by m-murad** [comment]
I have created this as a gci task.
One of the student will do this.

**Comment by shubhamvashisht** [comment]
@m-murad  still we have to choose between Travis and circle. what do you say?

**Comment by nimit95** [comment]
I think we should prefer Travis.

**Comment by piyush6348** [comment]
yes @nimit95

**Comment by garg-anuj** [comment]
@m-murad task is about tool integration in repos in general or this one specific?

**Comment by m-murad** [comment]
@garg-anuj
Two separate tasks for Travis and codecov.
@shubhamvashisht
I would suggest Travis because more examples would be available for students to learn for.

**Comment by shubhamvashisht** [comment]
Should we open a separate issue for Travis integration?

**Comment by garg-anuj** [comment]
@piyush6348 add travis to this repo for now

**Comment by m-murad** [comment]
Let's add Travis to the repo like anuj said

**Comment by piyush6348** [comment]
ok @garg-anuj

**Comment by piyush6348** [comment]
@garg-anuj . Can you give me organization access for that?

**Comment by garg-anuj** [comment]
You just gotta need to add .travis.yml file. rest is everything set already. icon link is https://travis-ci.org/jboss-outreach/rest-android.svg?branch=master

**Comment by garg-anuj** [comment]
Fixed with #3
