### ISSUE TITLE
Design logo For Rest android app

### ISSUE THREAD

**Issue by Dominic1234** [jboss-outreach/rest-android#81]
![icon 480x480](https://user-images.githubusercontent.com/15064978/34673133-35b090c2-f4a7-11e7-848b-b2a0a2ee3dc3.png)
![icon 800x800](https://user-images.githubusercontent.com/15064978/34673136-35e5c80a-f4a7-11e7-9f1a-4d804f776121.png)
![icon 960x960](https://user-images.githubusercontent.com/15064978/34673137-361b2e46-f4a7-11e7-8dae-c5476d097209.png)

Are These All right?

**Comment by Dominic1234** [comment]
![icon](https://user-images.githubusercontent.com/15064978/34675171-bb978c66-f4ae-11e7-8ddb-02ba2aff92c5.png)
Is this ok?

**Comment by Dominic1234** [comment]
![icon](https://user-images.githubusercontent.com/15064978/34675171-bb978c66-f4ae-11e7-8ddb-02ba2aff92c5.png)
Is this ok?

**Comment by Dominic1234** [comment]
![icon](https://user-images.githubusercontent.com/15064978/34675171-bb978c66-f4ae-11e7-8ddb-02ba2aff92c5.png)
Is this ok?

**Comment by Dominic1234** [comment]
<img width="24" alt="mdpi" src="https://user-images.githubusercontent.com/15064978/34727507-247a817e-f57d-11e7-858c-441ef81a613c.png">
<img width="36" alt="hdpi" src="https://user-images.githubusercontent.com/15064978/34727508-25025518-f57d-11e7-998d-7b161cb9369b.png">
<img width="48" alt="xhdpi" src="https://user-images.githubusercontent.com/15064978/34727511-260ca972-f57d-11e7-8543-887208f3edca.png">
<img width="72" alt="xxhdpi" src="https://user-images.githubusercontent.com/15064978/34727514-270c91b6-f57d-11e7-8b5f-bf3c9cae82cb.png">
Updated versions of the icon with different sizes.

**Comment by shubhamvashisht** [comment]
@Dominic1234  better. :+1:
